name: Assessment CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  validate-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Ephemeral CI Environment Variables
        run: |
          mkdir -p config
          #  For this isolated CI test, we use throwaway dummy values.
          echo "DATABASE_URL=postgresql://barq_app:CIDummyPass_99x@postgres:5432/barq_tasks" > config/app.env
          echo "REDIS_URL=redis://redis:6379/0" >> config/app.env
          echo "POSTGRES_PASSWORD=CIDummyPass_99x" >> config/app.env

      - name: Syntax and Compose Checks
        run: docker compose config

      - name: Build Images
        run: docker compose build

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'barq-assessment-app-01'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Start Environment
        run: docker compose up -d

      - name: Wait for Readiness and Validate
        run: |
          chmod +x validate.py
          ./validate.py
          
      - name: Failure Test (Chaos Engineering)
        run: |
          chmod +x failure_test.py
          ./failure_test.py